### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by ju1973** [mwganson/EasyReflector#1]
Hi, I'm a french user and when I try to use the macro freecad send this error message :

17:59:14  Traceback (most recent call last):
  File "C:/Users/STUDIO/AppData/Roaming/FreeCAD/Macro/EasyReflector.FCMacro", line 531, in <module>
    import EasyReflector as FP
  File "C:\Users\STUDIO\AppData\Local\Programs\FreeCAD 0.21\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
<class 'ModuleNotFoundError'>: No module named 'EasyReflector'

Do you have an issue please ?

**Comment by mwganson** [comment]
Did you put the .FCMacro file into your macro folder?  When it executes it should create a new file called EasyReflector.py, which needs to be in the macro folder in order for FreeCAD to be able to find it.  Otherwise the object will not be able to function when restored from a saved file and you will get that error message.

After the 1.0 FreeCAD release I will be able to convert this over to a .py file format.  In the current stable version the addon manager does not support the .py file name extension when installing macros, it converts them all to the .FCMacro extension, which python cannot see as a module.
